# Application Port
server:
  port: 8080

spring:
  # Database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jeongchaegi?serverTimezone=UTC
    username: ssafy
    password: ssafy
  # JPA
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  # batch
  batch:
    initialize-schema: always
    job:
      enabled: false
