# Application Port
server:
  port: 8081
# jwt

jwt:
  secretKey: ${SECRETKEY}

  access:
    expiration: 36000000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: Authorization

  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: Authorization_refresh

spring:
  redis:
    host: 3.36.131.236
    port: 6379


  #   OAuth 로그인
  security:
    oauth2:
      client:
        registration:

          kakao:
            client-id: ${CLIENT_ID}
            redirect-uri: http://www.jeongchaegi.com:8081/login/oauth2/code/kakao
            client-authentication-method: POST
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: authorization_code
            response-type: code
            scope:
              - profile_nickname
              - account_email
              - profile_image
            client_name: kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


  # Database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.36.131.236:3306/jeongchaegi?serverTimezone=Asia/Seoul
    username: ${USERNAME_MYSQL}
    password: ${PASSWORD_MYSQL}
  # JPA
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        default_batch_fetch_size: 100 #성능 최적화
  # batch
  batch:
    initialize-schema: always
    job:
      enabled: false
