# Application Port
server:
  port: 8081
# jwt

jwt:
  secretKey: asdfasdfasdf56454adfs

  access:
    expiration: 1800000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: Authorization

  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: Authorization_refresh

spring:
  redis:
    host: localhost
    port: 6379


  #   OAuth 로그인
  security:
    oauth2:
      client:
        registration:

          kakao:
            client-id: fcb05990a84d7cbf01eef4a5d55f8439
            redirect-uri: http://3.36.131.236:8081/login/oauth2/code/kakao
            client-authentication-method: POST
            client-secret: YKLc4lQmIWKZSzhPcbVeUJckYogzlb0y
            authorization-grant-type: authorization_code

            # 로컬 테스트용 카카오 정보
#          kakao:
#            client-id: 5bebd3961cec12296fc72d86729bffe8
#            redirect-uri: http://localhost:8081/login/oauth2/code/kakao
#            client-authentication-method: POST
#            authorization-grant-type: authorization_code

            scope:
              - profile_nickname
              - account_email
              - profile_image
            client_name: kakao


        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


  # Database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.36.131.236:3306/jeongchaegi?serverTimezone=UTC
#    url: jdbc:mysql://localhost:3306/jeongchaegi?serverTimezone=UTC
    username: root
    password: ssafy
  # JPA
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    #      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  # batch
  batch:
    initialize-schema: always
    job:
      enabled: false
