# Application Port
server:
  port: 8081
# jwt

jwt:
  secretKey: asdfasdfasdf56454adfs

  access:
    expiration: 1800000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: Authorization

  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: Authorization_refresh

spring:
  #   OAuth 로그인
  security:
    oauth2:
      client:
        registration:

          kakao:
            prompt: login
            client-id: fcb05990a84d7cbf01eef4a5d55f8439
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao
            client-authentication-method: POST
            client-secret: YKLc4lQmIWKZSzhPcbVeUJckYogzlb0y
            authorization-grant-type: authorization_code
            # http://localhost:8080/login/oauth2/code/kakao
            # http://localhost:8080/jeongchaegi/user/kakaologin
            scope:
              - profile_nickname
              - account_email
            client_name: kakao


        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


  # Database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jeongchaegi?serverTimezone=UTC
    username: ssafy
    password: ssafy
  # JPA
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  # Batch
  batch:
    job:
      names: ${job.name:NONE}
